dist: trusty

language: android
android:
  components:
    - build-tools-28.0.3
    - android-24

script:
  - ./gradlew clean :core:build :desktop:build report

after_success:
  - bash <(curl -s https://codecov.io/bash) -t fdb74fd7-f5ad-4d56-bf0a-43ec5a43f491
