dist: trusty

language: java
jdk: oraclejdk8
script:
  - ./gradlew :core:clean :desktop:clean :core:build :desktop:build

#after_success:
#  - ./gradlew report
#  - bash <(curl -s https://codecov.io/bash)
