dist: trusty

language: android
android:
  components:
    - build-tools-28.0.3
    - android-24

script:
  - ./gradlew clean :core:build :desktop:build report

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_DEPLOY_TOKEN

before_deploy:
  - ./gradlew :desktop:installer

deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_OAUTH_TOKEN
  file: desktop/build/installer/*
  skip_cleanup: true
  on:
    tags: true
