dist: trusty

language: android
android:
  components:
    - build-tools-28.0.3
    - android-24

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./gradlew clean :core:build :desktop:build report

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_DEPLOY_TOKEN
  - ./cc-test-reporter format-coverage build/reports/jacoco/report/report.xml -t jacoco
  - ./cc-test-reporter after-build

before_deploy:
  - ./gradlew :desktop:installer

deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_OAUTH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/desktop/build/installer/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
