dist: trusty

language: android
android:
  components:
    - build-tools-28.0.3
    - android-24

script:
  - ./gradlew clean :core:build :desktop:build

#after_success:
#  - ./gradlew report
#  - bash <(curl -s https://codecov.io/bash)
