dist: trusty

language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - android-24
    - build-tools-28.0.3

    script:
      - ./gradlew clean build report

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
